services:
  frontend:
    build: .
    container_name: frontend-despacho
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"

networks:
  default:
    driver: bridge
