server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Frontend React — manejo de rutas
    location / {
        try_files $uri $uri/ /index.html;
    }
}

# Proxy para Backend Ventas
server {
    listen 8080;
    server_name _;

    location / {
        proxy_pass http://10.0.2.162:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Proxy para Backend Despachos
server {
    listen 8081;
    server_name _;

    location / {
        proxy_pass http://10.0.2.162:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}