server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Necesario para que React Router funcione correctamente
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia el backend de Ventas (ajusta el puerto según tu app)
    location /api/ventas/ {
        proxy_pass http://10.0.2.162:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy hacia el backend de Despachos
    location /api/despachos/ {
        proxy_pass http://10.0.2.162:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}